version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: PostgresCont
    restart : always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver : local