service: user-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions : false
  stage : "dev"
  region : "us-east-1"
  httpApi:
    cors : true

functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /login
          method: post
  verify:
    handler: app/handler.Verify
    events:
      - httpApi:
          path: /verify
          method: post
  profile:
    handler: app/handler.Profile
    events:
      - httpApi:
          path: "/user"
          method: get
      - httpApi:
          path: "/user"
          method: put
      - httpApi:
          path: "/user"
          method : post
  cart:
    handler: app/handler.Cart
    events:
      - httpApi:
          path: "/cart"
          method: get
      - httpApi:
          path: "/cart"
          method: put
      - httpApi:
          path: "/cart"
          method : post
  payment:
    handler: app/handler.Payment
    events:
      - httpApi:
          path: "/payment"
          method: get
      - httpApi:
          path: "/payment"
          method: put
      - httpApi:
          path: "/payment"
          method : post

plugins:
  - serverless-offline
  - serverless-plugin-typescript